# -*- coding: utf-8 -*-
"""ai detect

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rtj8goh5qG788Ti2Iy66M76OpW-OHkve
"""

from fastapi import FastAPI, UploadFile, File
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import numpy as np
import uvicorn
import io
import os

app = FastAPI()

IMG_SIZE = (224, 224)
CLASS_NAMES = ['safe', 'nude', 'sexy']

# ✅ Sửa đường dẫn
model_path = r"C:\Users\longt\aidetect\model\my_model.keras"
model = load_model(model_path)

@app.get("/")
def home():
    return {"message": "NSFW Model API is running"}

@app.post("/predict/")
async def predict_image(file: UploadFile = File(...)):
    contents = await file.read()
    try:
        image = load_img(io.BytesIO(contents), target_size=IMG_SIZE)
    except Exception as e:
        return {"error": f"Lỗi đọc ảnh: {str(e)}"}

    img_array = img_to_array(image) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    preds = model.predict(img_array)
    class_index = int(np.argmax(preds))
    confidence = float(np.max(preds)) * 100
    result = CLASS_NAMES[class_index]

    return {
        "prediction": result,
        "confidence": f"{confidence:.2f}%"
    }

